// ----------------------------------------------------------------------------------
// <copyright company="Exesoft Inc.">
//	This code was generated by Instant Web API code automation software (https://www.InstantWebAPI.com)
//	Copyright Exesoft Inc. © 2019.  All rights reserved.
// </copyright>
// ----------------------------------------------------------------------------------

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace TenantAPI.Entities {
    
    
    public class AddressConfiguration : IEntityTypeConfiguration<Address> {
        
        private string _schema = "dbo";
        
        public virtual void Configure(EntityTypeBuilder<Address> builder) {
            Configure(builder, _schema);
        }
        
        private void Configure(EntityTypeBuilder<Address> builder, string schema) {
            builder.ToTable("Address", schema);
            builder.HasKey(x => x.Id);

            builder.Property(x => x.Id).HasColumnName(@"Id").HasColumnType("uniqueidentifier").IsRequired();
            builder.Property(x => x.UserId).HasColumnName(@"UserId").HasColumnType("nvarchar").IsRequired().HasMaxLength(50);
            builder.Property(x => x.AddressTypeId).HasColumnName(@"AddressTypeId").HasColumnType("int").IsRequired();
            builder.Property(x => x.StateId).HasColumnName(@"StateId").HasColumnType("int").IsRequired();
            builder.Property(x => x.AddressLine1).HasColumnName(@"AddressLine1").HasColumnType("nvarchar").IsRequired().HasMaxLength(100);
            builder.Property(x => x.AddressLine2).HasColumnName(@"AddressLine2").HasColumnType("nvarchar").IsRequired(false).HasMaxLength(100);
            builder.Property(x => x.City).HasColumnName(@"City").HasColumnType("nvarchar").IsRequired().HasMaxLength(50);
            builder.Property(x => x.PostalCode).HasColumnName(@"PostalCode").HasColumnType("nvarchar").IsRequired().HasMaxLength(50);
            builder.Property(x => x.IsDefault).HasColumnName(@"IsDefault").HasColumnType("bit").IsRequired();
            builder.Property(x => x.CreatedBy).HasColumnName(@"CreatedBy").HasColumnType("nvarchar").IsRequired().HasMaxLength(50);
            builder.Property(x => x.CreatedDate).HasColumnName(@"CreatedDate").HasColumnType("datetime").IsRequired();
            builder.Property(x => x.UpdatedBy).HasColumnName(@"UpdatedBy").HasColumnType("nvarchar").IsRequired(false).HasMaxLength(50);
            builder.Property(x => x.UpdatedDate).HasColumnName(@"UpdatedDate").HasColumnType("datetime").IsRequired(false);

            //Foreign keys
            builder.HasOne(a => a.AddressType).WithMany(b => b.Addresses).HasForeignKey(c => c.AddressTypeId); // FK_Address_AddressType
            builder.HasOne(a => a.State).WithMany(b => b.Addresses).HasForeignKey(c => c.StateId); // FK_Address_State
        }
    }
}

