// ----------------------------------------------------------------------------------
// <copyright company="Exesoft Inc.">
//	This code was generated by Instant Web API code automation software (https://www.InstantWebAPI.com)
//	Copyright Exesoft Inc. © 2019.  All rights reserved.
// </copyright>
// ----------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace TenantAPI.Entities {
    
    
    public partial class Address {
        
        [Key()]
        [Display(Name = "Id")]
        public System.Guid Id { get; set; }
        
        [Display(Name = "User ID")]
        public string UserId { get; set; }
        
        [Display(Name = "Address type ID")]
        public int AddressTypeId { get; set; }
        
        [Display(Name = "State ID")]
        public int StateId { get; set; }
        
        [Display(Name = "Address line 1")]
        public string AddressLine1 { get; set; }
        
        [Display(Name = "Address line 2")]
        public string AddressLine2 { get; set; }
        
        [Display(Name = "City")]
        public string City { get; set; }
        
        [Display(Name = "Postal code")]
        public string PostalCode { get; set; }
        
        [Display(Name = "Is default")]
        public bool IsDefault { get; set; }
        
        [Display(Name = "Created by")]
        public string CreatedBy { get; set; }
        
        [Display(Name = "Created date")]
        public System.DateTime CreatedDate { get; set; }
        
        [Display(Name = "Updated by")]
        public string UpdatedBy { get; set; }
        
        [Display(Name = "Updated date")]
        public System.DateTime? UpdatedDate { get; set; }
        
        // Parent AddressType pointed by [Address].([AddressTypeId]) (FK_Address_AddressType)
        public virtual AddressType AddressType { get; set; }
        
        // Parent State pointed by [Address].([StateId]) (FK_Address_State)
        public virtual State State { get; set; }
    }
}

