// ----------------------------------------------------------------------------------
// <copyright company="Exesoft Inc.">
//	This code was generated by Instant Web API code automation software (https://www.InstantWebAPI.com)
//	Copyright Exesoft Inc. © 2019.  All rights reserved.
// </copyright>
// ----------------------------------------------------------------------------------

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace TenantAPI.Entities {
    
    
    public class AuthProviderConfiguration : IEntityTypeConfiguration<AuthProvider> {
        
        private string _schema = "dbo";
        
        public virtual void Configure(EntityTypeBuilder<AuthProvider> builder) {
            Configure(builder, _schema);
        }
        
        private void Configure(EntityTypeBuilder<AuthProvider> builder, string schema) {
            builder.ToTable("AuthProvider", schema);
            builder.HasKey(x => x.Name);

            builder.Property(x => x.Name).HasColumnName(@"Name").HasColumnType("nvarchar").IsRequired().HasMaxLength(50);
            builder.Property(x => x.ClientId).HasColumnName(@"ClientId").HasColumnType("nvarchar").IsRequired().HasMaxLength(255);
            builder.Property(x => x.ClientSecret).HasColumnName(@"ClientSecret").HasColumnType("nvarchar").IsRequired().HasMaxLength(255);
            builder.Property(x => x.ClientEmail).HasColumnName(@"ClientEmail").HasColumnType("nvarchar").IsRequired(false).HasMaxLength(50);

            //Foreign keys
        }
    }
}

