// ----------------------------------------------------------------------------------
// <copyright company="Exesoft Inc.">
//	This code was generated by Instant Web API code automation software (https://www.InstantWebAPI.com)
//	Copyright Exesoft Inc. © 2019.  All rights reserved.
// </copyright>
// ----------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace TenantAPI.Entities {
    
    
    public partial class AuthProvider {
        
        [Key()]
        [Display(Name = "Name")]
        public string Name { get; set; }
        
        [Display(Name = "Client ID")]
        public string ClientId { get; set; }
        
        [Display(Name = "Client secret")]
        public string ClientSecret { get; set; }
        
        [Display(Name = "Client email")]
        public string ClientEmail { get; set; }
        
        /// Child Users where [User].[AuthProvider] point to this entity (FK_User_AuthProvider)
        public virtual ICollection<User> Users { get; set; } = new HashSet<User>();
    }
}

