// ----------------------------------------------------------------------------------
// <copyright company="Exesoft Inc.">
//	This code was generated by Instant Web API code automation software (https://www.InstantWebAPI.com)
//	Copyright Exesoft Inc. © 2019.  All rights reserved.
// </copyright>
// ----------------------------------------------------------------------------------

using Microsoft.EntityFrameworkCore;
using System;

namespace TenantAPI.Entities {
    
    
    public interface IDbEntities : IDbEntityBase {
        
        DbSet<Address> Addresses {
            get;
            set;
        }
        
        DbSet<AddressType> AddressTypes {
            get;
            set;
        }
        
        DbSet<AuthProvider> AuthProviders {
            get;
            set;
        }
        
        DbSet<Info> Infoes {
            get;
            set;
        }
        
        DbSet<Role> Roles {
            get;
            set;
        }
        
        DbSet<State> States {
            get;
            set;
        }
        
        DbSet<Tenant> Tenants {
            get;
            set;
        }
        
        DbSet<User> Users {
            get;
            set;
        }
        
        DbSet<UserRole> UserRoles {
            get;
            set;
        }
        
        DbSet<UserTitle> UserTitles {
            get;
            set;
        }
    }
}

