// ----------------------------------------------------------------------------------
// <copyright company="Exesoft Inc.">
//	This code was generated by Instant Web API code automation software (https://www.InstantWebAPI.com)
//	Copyright Exesoft Inc. © 2019.  All rights reserved.
// </copyright>
// ----------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace TenantAPI.Entities {
    
    
    public partial class Info {
        
        [Key()]
        [Display(Name = "Id")]
        public int Id { get; set; }
        
        [Display(Name = "Type")]
        public string Type { get; set; }
        
        [Display(Name = "Url")]
        public string Url { get; set; }
        
        [Display(Name = "Username")]
        public string Username { get; set; }
        
        [Display(Name = "Password")]
        public string Password { get; set; }
    }
}

