// ----------------------------------------------------------------------------------
// <copyright company="Exesoft Inc.">
//	This code was generated by Instant Web API code automation software (https://www.InstantWebAPI.com)
//	Copyright Exesoft Inc. © 2019.  All rights reserved.
// </copyright>
// ----------------------------------------------------------------------------------

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace TenantAPI.Entities {
    
    
    public class InfoConfiguration : IEntityTypeConfiguration<Info> {
        
        private string _schema = "dbo";
        
        public virtual void Configure(EntityTypeBuilder<Info> builder) {
            Configure(builder, _schema);
        }
        
        private void Configure(EntityTypeBuilder<Info> builder, string schema) {
            builder.ToTable("Info", schema);
            builder.HasKey(x => x.Id);

            builder.Property(x => x.Id).HasColumnName(@"Id").HasColumnType("int").IsRequired().ValueGeneratedOnAdd();
            builder.Property(x => x.Type).HasColumnName(@"Type").HasColumnType("nvarchar").IsRequired().HasMaxLength(50);
            builder.Property(x => x.Url).HasColumnName(@"Url").HasColumnType("nvarchar").IsRequired().HasMaxLength(256);
            builder.Property(x => x.Username).HasColumnName(@"Username").HasColumnType("nvarchar").IsRequired().HasMaxLength(50);
            builder.Property(x => x.Password).HasColumnName(@"Password").HasColumnType("nvarchar").IsRequired().HasMaxLength(250);

            //Foreign keys
        }
    }
}

