// ----------------------------------------------------------------------------------
// <copyright company="Exesoft Inc.">
//	This code was generated by Instant Web API code automation software (https://www.InstantWebAPI.com)
//	Copyright Exesoft Inc. © 2019.  All rights reserved.
// </copyright>
// ----------------------------------------------------------------------------------

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace TenantAPI.Entities {
    
    
    public class StateConfiguration : IEntityTypeConfiguration<State> {
        
        private string _schema = "dbo";
        
        public virtual void Configure(EntityTypeBuilder<State> builder) {
            Configure(builder, _schema);
        }
        
        private void Configure(EntityTypeBuilder<State> builder, string schema) {
            builder.ToTable("State", schema);
            builder.HasKey(x => x.Id);

            builder.Property(x => x.Id).HasColumnName(@"Id").HasColumnType("int").IsRequired().ValueGeneratedOnAdd();
            builder.Property(x => x.Abbreviation).HasColumnName(@"Abbreviation").HasColumnType("nvarchar").IsRequired().HasMaxLength(3);
            builder.Property(x => x.Name).HasColumnName(@"Name").HasColumnType("nvarchar").IsRequired().HasMaxLength(50);

            //Foreign keys
        }
    }
}

