// ----------------------------------------------------------------------------------
// <copyright company="Exesoft Inc.">
//	This code was generated by Instant Web API code automation software (https://www.InstantWebAPI.com)
//	Copyright Exesoft Inc. © 2019.  All rights reserved.
// </copyright>
// ----------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace TenantAPI.Entities {
    
    
    public partial class Tenant {
        
        [Key()]
        [Display(Name = "Id")]
        public System.Guid Id { get; set; }
        
        [Display(Name = "Company name")]
        public string CompanyName { get; set; }
        
        [Display(Name = "Website")]
        public string Website { get; set; }
        
        [Display(Name = "Database name")]
        public string DatabaseName { get; set; }
        
        [Display(Name = "Data source")]
        public string DataSource { get; set; }
        
        [Display(Name = "User ID")]
        public string UserId { get; set; }
        
        [Display(Name = "Password")]
        public string Password { get; set; }
        
        /// Child Users where [User].[TenantId] point to this entity (FK_User_Tenant)
        public virtual ICollection<User> Users { get; set; } = new HashSet<User>();
    }
}

