// ----------------------------------------------------------------------------------
// <copyright company="Exesoft Inc.">
//	This code was generated by Instant Web API code automation software (https://www.InstantWebAPI.com)
//	Copyright Exesoft Inc. © 2019.  All rights reserved.
// </copyright>
// ----------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace TenantAPI.Entities {
    
    
    public partial class UserTitle {
        
        [Key()]
        [Display(Name = "Title ID")]
        public int TitleId { get; set; }
        
        [Display(Name = "Abbreviation")]
        public string Abbreviation { get; set; }
        
        [Display(Name = "Description")]
        public string Description { get; set; }
        
        /// Child Users where [User].[TitleId] point to this entity (FK_User_UserTitle)
        public virtual ICollection<User> Users { get; set; } = new HashSet<User>();
    }
}

