// ----------------------------------------------------------------------------------
// <copyright company="Exesoft Inc.">
//	This code was generated by Instant Web API code automation software (https://www.InstantWebAPI.com)
//	Copyright Exesoft Inc. © 2019.  All rights reserved.
// </copyright>
// ----------------------------------------------------------------------------------

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace TenantAPI.Entities {
    
    
    public class UserTitleConfiguration : IEntityTypeConfiguration<UserTitle> {
        
        private string _schema = "dbo";
        
        public virtual void Configure(EntityTypeBuilder<UserTitle> builder) {
            Configure(builder, _schema);
        }
        
        private void Configure(EntityTypeBuilder<UserTitle> builder, string schema) {
            builder.ToTable("UserTitle", schema);
            builder.HasKey(x => x.TitleId);

            builder.Property(x => x.TitleId).HasColumnName(@"TitleId").HasColumnType("int").IsRequired().ValueGeneratedOnAdd();
            builder.Property(x => x.Abbreviation).HasColumnName(@"Abbreviation").HasColumnType("nvarchar").IsRequired().HasMaxLength(10);
            builder.Property(x => x.Description).HasColumnName(@"Description").HasColumnType("nvarchar").IsRequired(false).HasMaxLength(50);

            //Foreign keys
        }
    }
}

