// ----------------------------------------------------------------------------------
// <copyright company="Exesoft Inc.">
//	This code was generated by Instant Web API code automation software (https://www.InstantWebAPI.com)
//	Copyright Exesoft Inc. © 2019.  All rights reserved.
// </copyright>
// ----------------------------------------------------------------------------------

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace TenantAPI.Entities {
    
    
    public class UserRoleConfiguration : IEntityTypeConfiguration<UserRole> {
        
        private string _schema = "dbo";
        
        public virtual void Configure(EntityTypeBuilder<UserRole> builder) {
            Configure(builder, _schema);
        }
        
        private void Configure(EntityTypeBuilder<UserRole> builder, string schema) {
            builder.ToTable("UserRole", schema);
            builder.HasKey(x => new { x.RoleId, x.UserId });

            builder.Property(x => x.RoleId).HasColumnName(@"RoleId").HasColumnType("int").IsRequired();
            builder.Property(x => x.UserId).HasColumnName(@"UserId").HasColumnType("nvarchar").IsRequired().HasMaxLength(50);

            //Foreign keys
            builder.HasOne(a => a.Role).WithMany(b => b.UserRoles).HasForeignKey(c => c.RoleId); // FK_UserRole_Role
            builder.HasOne(a => a.User).WithMany(b => b.UserRoles).HasForeignKey(c => c.UserId); // FK_UserRole_User
        }
    }
}

