// ----------------------------------------------------------------------------------
// <copyright company="Exesoft Inc.">
//	This code was generated by Instant Web API code automation software (https://www.InstantWebAPI.com)
//	Copyright Exesoft Inc. © 2019.  All rights reserved.
// </copyright>
// ----------------------------------------------------------------------------------

using InstantHelper;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Data;
using System.Dynamic;
using System.Linq;
using System.Threading.Tasks;
using TenantAPI.Models;
using TenantAPI.Services;

namespace TenantAPI.Controllers {
    
    
    // TODO: Uncomment the following line to use an API Key; change the value of the key in appSetting (X-API-Key)
    // [ApiKey()]
    [Route("AuthProvider")]
    public class AuthProviderController : ControllerBase {
        
        private IAuthProviderBuilder _builder;
        
        public AuthProviderController(IAuthProviderBuilder builder) {
            _builder = builder;
        }
        
        [HttpGet("")]
        public async Task<ActionResult> GetAuthProviders() {

            return Ok(await _builder.GetAuthProviders());
        }
        
        [HttpGet("Display")]
        public async Task<ActionResult> GetDisplayModels() {
            //List all model properties that should be displayed
            //Here only a couple have been added as an example
            var propNames = new List<string>();
            propNames.Add(nameof(AuthProviderModel.Name));
            propNames.Add(nameof(AuthProviderModel.ClientId));

            return Ok(await Task.FromResult(_builder.GetDisplayModels(propNames)));
        }
        
        [HttpGet("Paged")]
        public async Task<ActionResult> Paged(int pageIndex, int pageSize) {

            var models = await _builder.GetAuthProviders();

            return Ok(models.ToPagedList(pageIndex, pageSize, 0, models.Count()));
        }
        
        [HttpGet("{name}")]
        public async Task<ActionResult> GetAuthProvider_ByName(string name) {

             var response = await _builder.GetAuthProvider_ByName(name);
            if (response.ValidationMessage != null) {
                return BadRequest(response.ValidationMessage);
            }

            return Ok(response.Model);
        }
        
        [HttpPost("")]
        [ModelStateValidation()]
        public async Task<ActionResult> AddAuthProvider([FromBody]AuthProviderModel model) {

            var response = await _builder.AddAuthProvider(model);

            if (response.ValidationMessage != null) {
                return BadRequest(response.ValidationMessage);
            }

            return CreatedAtAction("GetAuthProvider_ByName", new {name = ((AuthProviderModel)response.Model).Name}, response.Model);
        }
        
        [HttpPut("")]
        [ModelStateValidation()]
        public async Task<ActionResult> UpdateAuthProvider([FromBody]AuthProviderModel model) {
            var response = await _builder.UpdateAuthProvider(model);

            if (response.ValidationMessage != null) {
                return BadRequest(response.ValidationMessage);
            }

            return AcceptedAtAction("GetAuthProvider_ByName", new {name = model.Name}, model);
        }
        
        [HttpDelete("{name}")]
        public async Task<ActionResult> DeleteAuthProvider(string name) {

            var response = await _builder.DeleteAuthProvider(name);

            if (response.ValidationMessage != null) {
                return BadRequest(response.ValidationMessage);
            }

            return StatusCode(response.StatusCode);
        }
    }
}

