// ----------------------------------------------------------------------------------
// <copyright company="Exesoft Inc.">
//	This code was generated by Instant Web API code automation software (https://www.InstantWebAPI.com)
//	Copyright Exesoft Inc. © 2019.  All rights reserved.
// </copyright>
// ----------------------------------------------------------------------------------

using InstantHelper;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Data;
using System.Dynamic;
using System.Linq;
using System.Threading.Tasks;
using TenantAPI.Models;
using TenantAPI.Services;

namespace TenantAPI.Controllers {
    
    
    // TODO: Uncomment the following line to use an API Key; change the value of the key in appSetting (X-API-Key)
    // [ApiKey()]
    [Route("User")]
    public class UserController : ControllerBase {
        
        private IUserBuilder _builder;
        
        public UserController(IUserBuilder builder) {
            _builder = builder;
        }
        
        [HttpGet("")]
        public async Task<ActionResult> GetUsers() {

            return Ok(await _builder.GetUsers());
        }
        
        [HttpGet("Display")]
        public async Task<ActionResult> GetDisplayModels() {
            //List all model properties that should be displayed
            //Here only a couple have been added as an example
            var propNames = new List<string>();
            propNames.Add(nameof(UserModel.Id));
            propNames.Add(nameof(UserModel.TenantId));

            return Ok(await Task.FromResult(_builder.GetDisplayModels(propNames)));
        }
        
        [HttpGet("Paged")]
        public async Task<ActionResult> Paged(int pageIndex, int pageSize) {

            var models = await _builder.GetUsers();

            return Ok(models.ToPagedList(pageIndex, pageSize, 0, models.Count()));
        }
        
        [HttpGet("{id}")]
        public async Task<ActionResult> GetUser_ById(string id) {

             var response = await _builder.GetUser_ById(id);
            if (response.ValidationMessage != null) {
                return BadRequest(response.ValidationMessage);
            }

            return Ok(response.Model);
        }
        
        [HttpGet("GetUser_ByTenantId/{tenantId}")]
        public async Task<IQueryable<UserModel>> GetUser_ByTenantId(System.Guid tenantId) {

            return await _builder.GetUser_ByTenantId(tenantId);
        }
        
        [HttpGet("GetUser_ByAuthProvider/{authProvider}")]
        public async Task<IQueryable<UserModel>> GetUser_ByAuthProvider(string authProvider) {

            return await _builder.GetUser_ByAuthProvider(authProvider);
        }
        
        [HttpGet("GetUser_ByTitleId/{titleId}")]
        public async Task<IQueryable<UserModel>> GetUser_ByTitleId(int titleId) {

            return await _builder.GetUser_ByTitleId(titleId);
        }
        
        [HttpPost("")]
        [ModelStateValidation()]
        public async Task<ActionResult> AddUser([FromBody]UserModel model) {

            var response = await _builder.AddUser(model);

            if (response.ValidationMessage != null) {
                return BadRequest(response.ValidationMessage);
            }

            return CreatedAtAction("GetUser_ById", new {id = ((UserModel)response.Model).Id}, response.Model);
        }
        
        [HttpPut("")]
        [ModelStateValidation()]
        public async Task<ActionResult> UpdateUser([FromBody]UserModel model) {
            var response = await _builder.UpdateUser(model);

            if (response.ValidationMessage != null) {
                return BadRequest(response.ValidationMessage);
            }

            return AcceptedAtAction("GetUser_ById", new {id = model.Id}, model);
        }
        
        [HttpDelete("{id}")]
        public async Task<ActionResult> DeleteUser(string id) {

            var response = await _builder.DeleteUser(id);

            if (response.ValidationMessage != null) {
                return BadRequest(response.ValidationMessage);
            }

            return StatusCode(response.StatusCode);
        }
    }
}

