// ----------------------------------------------------------------------------------
// <copyright company="Exesoft Inc.">
//	This code was generated by Instant Web API code automation software (https://www.InstantWebAPI.com)
//	Copyright Exesoft Inc. © 2019.  All rights reserved.
// </copyright>
// ----------------------------------------------------------------------------------

using InstantHelper;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Data;
using System.Dynamic;
using System.Linq;
using System.Threading.Tasks;
using TenantAPI.Models;
using TenantAPI.Services;

namespace TenantAPI.Controllers {
    
    
    // TODO: Uncomment the following line to use an API Key; change the value of the key in appSetting (X-API-Key)
    // [ApiKey()]
    [Route("UserTitle")]
    public class UserTitleController : ControllerBase {
        
        private IUserTitleBuilder _builder;
        
        public UserTitleController(IUserTitleBuilder builder) {
            _builder = builder;
        }
        
        [HttpGet("")]
        public async Task<ActionResult> GetUserTitles() {

            return Ok(await _builder.GetUserTitles());
        }
        
        [HttpGet("Display")]
        public async Task<ActionResult> GetDisplayModels() {
            //List all model properties that should be displayed
            //Here only a couple have been added as an example
            var propNames = new List<string>();
            propNames.Add(nameof(UserTitleModel.TitleId));
            propNames.Add(nameof(UserTitleModel.Abbreviation));

            return Ok(await Task.FromResult(_builder.GetDisplayModels(propNames)));
        }
        
        [HttpGet("Paged")]
        public async Task<ActionResult> Paged(int pageIndex, int pageSize) {

            var models = await _builder.GetUserTitles();

            return Ok(models.ToPagedList(pageIndex, pageSize, 0, models.Count()));
        }
        
        [HttpGet("{titleId}")]
        public async Task<ActionResult> GetUserTitle_ByTitleId(int titleId) {

             var response = await _builder.GetUserTitle_ByTitleId(titleId);
            if (response.ValidationMessage != null) {
                return BadRequest(response.ValidationMessage);
            }

            return Ok(response.Model);
        }
        
        [HttpPost("")]
        [ModelStateValidation()]
        public async Task<ActionResult> AddUserTitle([FromBody]UserTitleModel model) {

            var response = await _builder.AddUserTitle(model);

            if (response.ValidationMessage != null) {
                return BadRequest(response.ValidationMessage);
            }

            return CreatedAtAction("GetUserTitle_ByTitleId", new {titleId = ((UserTitleModel)response.Model).TitleId}, response.Model);
        }
        
        [HttpPut("")]
        [ModelStateValidation()]
        public async Task<ActionResult> UpdateUserTitle([FromBody]UserTitleModel model) {
            var response = await _builder.UpdateUserTitle(model);

            if (response.ValidationMessage != null) {
                return BadRequest(response.ValidationMessage);
            }

            return AcceptedAtAction("GetUserTitle_ByTitleId", new {titleId = model.TitleId}, model);
        }
        
        [HttpDelete("{titleId}")]
        public async Task<ActionResult> DeleteUserTitle(int titleId) {

            var response = await _builder.DeleteUserTitle(titleId);

            if (response.ValidationMessage != null) {
                return BadRequest(response.ValidationMessage);
            }

            return StatusCode(response.StatusCode);
        }
    }
}

