// ----------------------------------------------------------------------------------
// <copyright company="Exesoft Inc.">
//	This code was generated by Instant Web API code automation software (https://www.InstantWebAPI.com)
//	Copyright Exesoft Inc. © 2019.  All rights reserved.
// </copyright>
// ----------------------------------------------------------------------------------

using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Data;
using System.Dynamic;
using System.Linq;
using System.Linq.Expressions;
using System.Net;
using System.Threading.Tasks;
using TenantAPI.Entities;
using TenantAPI.Models;
using TenantAPI.Services;

namespace TenantAPI.Services {
    
    
    public class AuthProviderBuilder : IAuthProviderBuilder {
        
        private IDbEntities _entities;
        
        private ILoggerManager _logger;
        
        public AuthProviderBuilder(EntitiesContext context, ILoggerManager logger) {
            _entities = context;
            _logger = logger;
        }
        
        private Expression<Func<AuthProvider, AuthProviderModel>>  ProjectToModel {
            get {
                return entity => new AuthProviderModel(entity);
            }
        }
        
        public async Task<IQueryable<AuthProviderModel>> GetAuthProviders() {
            return await Task.FromResult(_entities.AuthProviders.Select(ProjectToModel));
        }
        
        public IList<ExpandoObject> GetDisplayModels(List<string> propNames) {
            var models = _entities.AuthProviders.Select(ProjectToModel);

            var displayModels = new List<ExpandoObject>();
            foreach (var model in models)
            {
                dynamic displayModel = DynamicHelper.ConvertToExpando(model, propNames);
                displayModels.Add(displayModel);
            }

            return displayModels;
        }
        
        public async Task<BuilderResponse> GetAuthProvider_ByName(string name) {
            var query = Search(_entities.AuthProviders, x => x.Name == name).Select(ProjectToModel);
            if (query.Any()) {
                return await Task.FromResult(new BuilderResponse{ Model = query.Single() }); 
            }
            else {
                return await Task.FromResult(new BuilderResponse { ValidationMessage = $"Record Not Found; AuthProvider with name = '{name}' doesn't exist." }); 
            }
        }
        
        public async Task<BuilderResponse> AddAuthProvider(AuthProviderModel model) {


            var entity = ModelExtender.ToEntity(model);
            _entities.AuthProviders.Add(entity);
            await _entities.SaveChangesAsync();
            _logger.LogInfo(string.Format("AuthProvider added with values: '{0}'", JsonConvert.SerializeObject(model)));

            return new BuilderResponse{ Model = new AuthProviderModel(entity) }; 
        }
        
        public async Task<BuilderResponse> UpdateAuthProvider(AuthProviderModel model) {

            var query = Search(_entities.AuthProviders, x =>  x.Name == model.Name);
            if (!query.Any()) {
            return new BuilderResponse { ValidationMessage = "Record Not Found; " + string.Format("AuthProvider with _name = '{0}' doesn't exist.",model.Name)}; 
            }

            AuthProvider entity = query.SingleOrDefault();

            entity = model.ToEntity(entity);
            await _entities.SaveChangesAsync();
            _logger.LogInfo(string.Format("AuthProvider update with values: '{0}'", JsonConvert.SerializeObject(model)));

            return new BuilderResponse{ StatusCode = (int)HttpStatusCode.Accepted }; 
        }
        
        public async Task<BuilderResponse> DeleteAuthProvider(string name) {

            var query = Search(_entities.AuthProviders, x => x.Name == name);
            if (!query.Any()) {
                return new BuilderResponse { ValidationMessage = "Record Not Found; " + string.Format("AuthProvider with _name = '{0}' doesn't exist.",name)}; 
            }

            var entity = query.SingleOrDefault();

            _entities.AuthProviders.Remove(entity);
            await _entities.SaveChangesAsync();
            _logger.LogInfo(string.Format("AuthProvider deleted with values: '{0}'", JsonConvert.SerializeObject(new AuthProviderModel(entity))));

            return new BuilderResponse{ StatusCode = (int)HttpStatusCode.NoContent }; 
        }
        
        private IQueryable<AuthProvider> Search(IQueryable<AuthProvider> query, Expression<Func<AuthProvider, bool>> filter) {
            return query.Where(filter);
        }
    }
}

