// ----------------------------------------------------------------------------------
// <copyright company="Exesoft Inc.">
//	This code was generated by Instant Web API code automation software (https://www.InstantWebAPI.com)
//	Copyright Exesoft Inc. © 2019.  All rights reserved.
// </copyright>
// ----------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Dynamic;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using TenantAPI.Models;

namespace TenantAPI.Services {
    
    
    public interface IAddressTypeBuilder {
        
        Task<IQueryable<AddressTypeModel>> GetAddressTypes();
        
        IList<ExpandoObject> GetDisplayModels(List<string> propNames);
        
        Task<BuilderResponse> GetAddressType_ById(int id);
        
        Task<BuilderResponse> AddAddressType(AddressTypeModel model);
        
        Task<BuilderResponse> UpdateAddressType(AddressTypeModel model);
        
        Task<BuilderResponse> DeleteAddressType(int id);
    }
}

