// ----------------------------------------------------------------------------------
// <copyright company="Exesoft Inc.">
//	This code was generated by Instant Web API code automation software (https://www.InstantWebAPI.com)
//	Copyright Exesoft Inc. © 2019.  All rights reserved.
// </copyright>
// ----------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Dynamic;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using TenantAPI.Models;

namespace TenantAPI.Services {
    
    
    public interface IAddressBuilder {
        
        Task<IQueryable<AddressModel>> GetAddresses();
        
        IList<ExpandoObject> GetDisplayModels(List<string> propNames);
        
        Task<BuilderResponse> GetAddress_ById(System.Guid id);
        
        Task<IQueryable<AddressModel>> GetAddress_ByAddressTypeId(int addressTypeId);
        
        Task<IQueryable<AddressModel>> GetAddress_ByStateId(int stateId);
        
        Task<BuilderResponse> AddAddress(AddressModel model);
        
        Task<BuilderResponse> UpdateAddress(AddressModel model);
        
        Task<BuilderResponse> DeleteAddress(System.Guid id);
    }
}

