// ----------------------------------------------------------------------------------
// <copyright company="Exesoft Inc.">
//	This code was generated by Instant Web API code automation software (https://www.InstantWebAPI.com)
//	Copyright Exesoft Inc. © 2019.  All rights reserved.
// </copyright>
// ----------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Dynamic;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using TenantAPI.Models;

namespace TenantAPI.Services {
    
    
    public interface IInfoBuilder {
        
        Task<IQueryable<InfoModel>> GetInfoes();
        
        IList<ExpandoObject> GetDisplayModels(List<string> propNames);
        
        Task<BuilderResponse> GetInfo_ById(int id);
        
        Task<BuilderResponse> AddInfo(InfoModel model);
        
        Task<BuilderResponse> UpdateInfo(InfoModel model);
        
        Task<BuilderResponse> DeleteInfo(int id);
    }
}

