// ----------------------------------------------------------------------------------
// <copyright company="Exesoft Inc.">
//	This code was generated by Instant Web API code automation software (https://www.InstantWebAPI.com)
//	Copyright Exesoft Inc. © 2019.  All rights reserved.
// </copyright>
// ----------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Dynamic;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using TenantAPI.Models;

namespace TenantAPI.Services {
    
    
    public interface IRoleBuilder {
        
        Task<IQueryable<RoleModel>> GetRoles();
        
        IList<ExpandoObject> GetDisplayModels(List<string> propNames);
        
        Task<BuilderResponse> GetRole_ById(int id);
        
        Task<BuilderResponse> AddRole(RoleModel model);
        
        Task<BuilderResponse> UpdateRole(RoleModel model);
        
        Task<BuilderResponse> DeleteRole(int id);
    }
}

