// ----------------------------------------------------------------------------------
// <copyright company="Exesoft Inc.">
//	This code was generated by Instant Web API code automation software (https://www.InstantWebAPI.com)
//	Copyright Exesoft Inc. © 2019.  All rights reserved.
// </copyright>
// ----------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Dynamic;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using TenantAPI.Models;

namespace TenantAPI.Services {
    
    
    public interface IStateBuilder {
        
        Task<IQueryable<StateModel>> GetStates();
        
        IList<ExpandoObject> GetDisplayModels(List<string> propNames);
        
        Task<BuilderResponse> GetState_ById(int id);
        
        Task<BuilderResponse> AddState(StateModel model);
        
        Task<BuilderResponse> UpdateState(StateModel model);
        
        Task<BuilderResponse> DeleteState(int id);
    }
}

