// ----------------------------------------------------------------------------------
// <copyright company="Exesoft Inc.">
//	This code was generated by Instant Web API code automation software (https://www.InstantWebAPI.com)
//	Copyright Exesoft Inc. © 2019.  All rights reserved.
// </copyright>
// ----------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Dynamic;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using TenantAPI.Models;

namespace TenantAPI.Services {
    
    
    public interface ITenantBuilder {
        
        Task<IQueryable<TenantModel>> GetTenants();
        
        IList<ExpandoObject> GetDisplayModels(List<string> propNames);
        
        Task<BuilderResponse> GetTenant_ById(System.Guid id);
        
        Task<BuilderResponse> AddTenant(TenantModel model);
        
        Task<BuilderResponse> UpdateTenant(TenantModel model);
        
        Task<BuilderResponse> DeleteTenant(System.Guid id);
    }
}

