// ----------------------------------------------------------------------------------
// <copyright company="Exesoft Inc.">
//	This code was generated by Instant Web API code automation software (https://www.InstantWebAPI.com)
//	Copyright Exesoft Inc. © 2019.  All rights reserved.
// </copyright>
// ----------------------------------------------------------------------------------

using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Data;
using System.Dynamic;
using System.Linq;
using System.Linq.Expressions;
using System.Net;
using System.Threading.Tasks;
using TenantAPI.Entities;
using TenantAPI.Models;
using TenantAPI.Services;

namespace TenantAPI.Services {
    
    
    public class RoleBuilder : IRoleBuilder {
        
        private IDbEntities _entities;
        
        private ILoggerManager _logger;
        
        public RoleBuilder(EntitiesContext context, ILoggerManager logger) {
            _entities = context;
            _logger = logger;
        }
        
        private Expression<Func<Role, RoleModel>>  ProjectToModel {
            get {
                return entity => new RoleModel(entity);
            }
        }
        
        public async Task<IQueryable<RoleModel>> GetRoles() {
            return await Task.FromResult(_entities.Roles.Select(ProjectToModel));
        }
        
        public IList<ExpandoObject> GetDisplayModels(List<string> propNames) {
            var models = _entities.Roles.Select(ProjectToModel);

            var displayModels = new List<ExpandoObject>();
            foreach (var model in models)
            {
                dynamic displayModel = DynamicHelper.ConvertToExpando(model, propNames);
                displayModels.Add(displayModel);
            }

            return displayModels;
        }
        
        public async Task<BuilderResponse> GetRole_ById(int id) {
            var query = Search(_entities.Roles, x => x.Id == id).Select(ProjectToModel);
            if (query.Any()) {
                return await Task.FromResult(new BuilderResponse{ Model = query.Single() }); 
            }
            else {
                return await Task.FromResult(new BuilderResponse { ValidationMessage = $"Record Not Found; Role with id = '{id}' doesn't exist." }); 
            }
        }
        
        public async Task<BuilderResponse> AddRole(RoleModel model) {


            var entity = ModelExtender.ToEntity(model);
            _entities.Roles.Add(entity);
            await _entities.SaveChangesAsync();
            _logger.LogInfo(string.Format("Role added with values: '{0}'", JsonConvert.SerializeObject(model)));

            return new BuilderResponse{ Model = new RoleModel(entity) }; 
        }
        
        public async Task<BuilderResponse> UpdateRole(RoleModel model) {

            var query = Search(_entities.Roles, x =>  x.Id == model.Id);
            if (!query.Any()) {
                return new BuilderResponse { ValidationMessage = "Record Not Found; " + string.Format("Role with _id = '{0}' doesn't exist.",model.Id)}; 
            }

            Role entity = query.SingleOrDefault();
            entity = model.ToEntity(entity);
            await _entities.SaveChangesAsync();
            _logger.LogInfo(string.Format("Role update with values: '{0}'", JsonConvert.SerializeObject(model)));

            return new BuilderResponse{ StatusCode = (int)HttpStatusCode.Accepted }; 
        }
        
        public async Task<BuilderResponse> DeleteRole(int id) {

            var query = Search(_entities.Roles, x => x.Id == id);
            if (!query.Any()) {
                return new BuilderResponse { ValidationMessage = "Record Not Found; " + string.Format("Role with _id = '{0}' doesn't exist.",id)}; 
            }

            var entity = query.SingleOrDefault();

            _entities.Roles.Remove(entity);
            await _entities.SaveChangesAsync();
            _logger.LogInfo(string.Format("Role deleted with values: '{0}'", JsonConvert.SerializeObject(new RoleModel(entity))));

            return new BuilderResponse{ StatusCode = (int)HttpStatusCode.NoContent }; 
        }
        
        private IQueryable<Role> Search(IQueryable<Role> query, Expression<Func<Role, bool>> filter) {
            return query.Where(filter);
        }
    }
}

