// ----------------------------------------------------------------------------------
// <copyright company="Exesoft Inc.">
//	This code was generated by Instant Web API code automation software (https://www.InstantWebAPI.com)
//	Copyright Exesoft Inc. © 2019.  All rights reserved.
// </copyright>
// ----------------------------------------------------------------------------------

using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Data;
using System.Dynamic;
using System.Linq;
using System.Linq.Expressions;
using System.Net;
using System.Threading.Tasks;
using TenantAPI.Entities;
using TenantAPI.Models;
using TenantAPI.Services;

namespace TenantAPI.Services {
    
    
    public class TenantBuilder : ITenantBuilder {
        
        private IDbEntities _entities;
        
        private ILoggerManager _logger;
        
        public TenantBuilder(EntitiesContext context, ILoggerManager logger) {
            _entities = context;
            _logger = logger;
        }
        
        private Expression<Func<Tenant, TenantModel>>  ProjectToModel {
            get {
                return entity => new TenantModel(entity);
            }
        }
        
        public async Task<IQueryable<TenantModel>> GetTenants() {
            return await Task.FromResult(_entities.Tenants.Select(ProjectToModel));
        }
        
        public IList<ExpandoObject> GetDisplayModels(List<string> propNames) {
            var models = _entities.Tenants.Select(ProjectToModel);

            var displayModels = new List<ExpandoObject>();
            foreach (var model in models)
            {
                dynamic displayModel = DynamicHelper.ConvertToExpando(model, propNames);
                displayModels.Add(displayModel);
            }

            return displayModels;
        }
        
        public async Task<BuilderResponse> GetTenant_ById(System.Guid id) {
            var query = Search(_entities.Tenants, x => x.Id == id).Select(ProjectToModel);
            if (query.Any()) {
                return await Task.FromResult(new BuilderResponse{ Model = query.Single() }); 
            }
            else {
                return await Task.FromResult(new BuilderResponse { ValidationMessage = $"Record Not Found; Tenant with id = '{id}' doesn't exist." }); 
            }
        }
        
        public async Task<BuilderResponse> AddTenant(TenantModel model) {


            var entity = ModelExtender.ToEntity(model);
            _entities.Tenants.Add(entity);
            await _entities.SaveChangesAsync();
            _logger.LogInfo(string.Format("Tenant added with values: '{0}'", JsonConvert.SerializeObject(model)));

            return new BuilderResponse{ Model = new TenantModel(entity) }; 
        }
        
        public async Task<BuilderResponse> UpdateTenant(TenantModel model) {

            var query = Search(_entities.Tenants, x =>  x.Id == model.Id);
            if (!query.Any()) {
            return new BuilderResponse { ValidationMessage = "Record Not Found; " + string.Format("Tenant with _id = '{0}' doesn't exist.",model.Id)}; 
            }

            Tenant entity = query.SingleOrDefault();

            entity = model.ToEntity(entity);
            await _entities.SaveChangesAsync();
            _logger.LogInfo(string.Format("Tenant update with values: '{0}'", JsonConvert.SerializeObject(model)));

            return new BuilderResponse{ StatusCode = (int)HttpStatusCode.Accepted }; 
        }
        
        public async Task<BuilderResponse> DeleteTenant(System.Guid id) {

            var query = Search(_entities.Tenants, x => x.Id == id);
            if (!query.Any()) {
                return new BuilderResponse { ValidationMessage = "Record Not Found; " + string.Format("Tenant with _id = '{0}' doesn't exist.",id)}; 
            }

            var entity = query.SingleOrDefault();

            _entities.Tenants.Remove(entity);
            await _entities.SaveChangesAsync();
            _logger.LogInfo(string.Format("Tenant deleted with values: '{0}'", JsonConvert.SerializeObject(new TenantModel(entity))));

            return new BuilderResponse{ StatusCode = (int)HttpStatusCode.NoContent }; 
        }
        
        private IQueryable<Tenant> Search(IQueryable<Tenant> query, Expression<Func<Tenant, bool>> filter) {
            return query.Where(filter);
        }
    }
}

