// ----------------------------------------------------------------------------------
// <copyright company="Exesoft Inc.">
//	This code was generated by Instant Web API code automation software (https://www.InstantWebAPI.com)
//	Copyright Exesoft Inc. © 2019.  All rights reserved.
// </copyright>
// ----------------------------------------------------------------------------------

using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Data;
using System.Dynamic;
using System.Linq;
using System.Linq.Expressions;
using System.Net;
using System.Threading.Tasks;
using TenantAPI.Entities;
using TenantAPI.Models;
using TenantAPI.Services;

namespace TenantAPI.Services {
    
    
    public class UserTitleBuilder : IUserTitleBuilder {
        
        private IDbEntities _entities;
        
        private ILoggerManager _logger;
        
        public UserTitleBuilder(EntitiesContext context, ILoggerManager logger) {
            _entities = context;
            _logger = logger;
        }
        
        private Expression<Func<UserTitle, UserTitleModel>>  ProjectToModel {
            get {
                return entity => new UserTitleModel(entity);
            }
        }
        
        public async Task<IQueryable<UserTitleModel>> GetUserTitles() {
            return await Task.FromResult(_entities.UserTitles.Select(ProjectToModel));
        }
        
        public IList<ExpandoObject> GetDisplayModels(List<string> propNames) {
            var models = _entities.UserTitles.Select(ProjectToModel);

            var displayModels = new List<ExpandoObject>();
            foreach (var model in models)
            {
                dynamic displayModel = DynamicHelper.ConvertToExpando(model, propNames);
                displayModels.Add(displayModel);
            }

            return displayModels;
        }
        
        public async Task<BuilderResponse> GetUserTitle_ByTitleId(int titleId) {
            var query = Search(_entities.UserTitles, x => x.TitleId == titleId).Select(ProjectToModel);
            if (query.Any()) {
                return await Task.FromResult(new BuilderResponse{ Model = query.Single() }); 
            }
            else {
                return await Task.FromResult(new BuilderResponse { ValidationMessage = $"Record Not Found; UserTitle with titleId = '{titleId}' doesn't exist." }); 
            }
        }
        
        public async Task<BuilderResponse> AddUserTitle(UserTitleModel model) {


            var entity = ModelExtender.ToEntity(model);
            _entities.UserTitles.Add(entity);
            await _entities.SaveChangesAsync();
            _logger.LogInfo(string.Format("UserTitle added with values: '{0}'", JsonConvert.SerializeObject(model)));

            return new BuilderResponse{ Model = new UserTitleModel(entity) }; 
        }
        
        public async Task<BuilderResponse> UpdateUserTitle(UserTitleModel model) {

            var query = Search(_entities.UserTitles, x =>  x.TitleId == model.TitleId);
            if (!query.Any()) {
                return new BuilderResponse { ValidationMessage = "Record Not Found; " + string.Format("UserTitle with _titleId = '{0}' doesn't exist.",model.TitleId)}; 
            }

            UserTitle entity = query.SingleOrDefault();
            entity = model.ToEntity(entity);
            await _entities.SaveChangesAsync();
            _logger.LogInfo(string.Format("UserTitle update with values: '{0}'", JsonConvert.SerializeObject(model)));

            return new BuilderResponse{ StatusCode = (int)HttpStatusCode.Accepted }; 
        }
        
        public async Task<BuilderResponse> DeleteUserTitle(int titleId) {

            var query = Search(_entities.UserTitles, x => x.TitleId == titleId);
            if (!query.Any()) {
                return new BuilderResponse { ValidationMessage = "Record Not Found; " + string.Format("UserTitle with _titleId = '{0}' doesn't exist.",titleId)}; 
            }

            var entity = query.SingleOrDefault();

            _entities.UserTitles.Remove(entity);
            await _entities.SaveChangesAsync();
            _logger.LogInfo(string.Format("UserTitle deleted with values: '{0}'", JsonConvert.SerializeObject(new UserTitleModel(entity))));

            return new BuilderResponse{ StatusCode = (int)HttpStatusCode.NoContent }; 
        }
        
        private IQueryable<UserTitle> Search(IQueryable<UserTitle> query, Expression<Func<UserTitle, bool>> filter) {
            return query.Where(filter);
        }
    }
}

