// ----------------------------------------------------------------------------------
// <copyright company="Exesoft Inc.">
//	This code was generated by Instant Web API code automation software (https://www.InstantWebAPI.com)
//	Copyright Exesoft Inc. © 2019.  All rights reserved.
// </copyright>
// ----------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using TenantAPI.Entities;
using TenantAPI.Models;

namespace TenantAPI.Models {
    
    
    public class AddressTypeModel {
        
        protected internal int _id;
        
        protected internal string _type;
        
        public AddressTypeModel() {
        }
        
        internal AddressTypeModel(AddressType entity) {
            this._id = entity.Id;
            this._type = entity.Type;
        }
        
        [Display(Name = "Id")]
        public int Id {
            get {
                return this._id;
            }
            set {
                this._id = value;
            }
        }
        
        [Required()]
        [MaxLength(50)]
        [StringLength(50)]
        [Display(Name = "Type")]
        public string Type {
            get {
                return this._type;
            }
            set {
                this._type = value;
            }
        }
        
        /// Child Addresses where [Address].[AddressTypeId] point to this entity (FK_Address_AddressType)
        public virtual ICollection<AddressModel> AddressesModel { get; set; } = new HashSet<AddressModel>();
        
        public override int GetHashCode() {
            int hash = 0;
            hash ^=Type.GetHashCode();
            return hash;
        }
        
        public override string ToString() {
            return Type
;
        }
        
        public override bool Equals(object obj) {
        bool result = false;

            if (obj is AddressTypeModel) {
                AddressTypeModel toCompare = (AddressTypeModel)obj;
              if(toCompare != null)
              {
                  result = Equals(toCompare);
              }
            }

            return result;
        }
        
        public virtual bool Equals(AddressTypeModel toCompare) {

        bool result = false;

            if (toCompare != null) {
                result = string.Compare(toCompare.Type, Type, true) == 0
;
            }

            return result;
        }
    }
}

