// ----------------------------------------------------------------------------------
// <copyright company="Exesoft Inc.">
//	This code was generated by Instant Web API code automation software (https://www.InstantWebAPI.com)
//	Copyright Exesoft Inc. © 2019.  All rights reserved.
// </copyright>
// ----------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using TenantAPI.Entities;
using TenantAPI.Models;

namespace TenantAPI.Models {
    
    
    public class AuthProviderModel {
        
        protected internal string _name;
        
        protected internal string _clientId;
        
        protected internal string _clientSecret;
        
        protected internal string _clientEmail;
        
        public AuthProviderModel() {
        }
        
        internal AuthProviderModel(AuthProvider entity) {
            this._name = entity.Name;
            this._clientId = entity.ClientId;
            this._clientSecret = entity.ClientSecret;
            this._clientEmail = entity.ClientEmail;
        }
        
        [Required()]
        [MaxLength(50)]
        [StringLength(50)]
        [Display(Name = "Name")]
        public string Name {
            get {
                return this._name;
            }
            set {
                this._name = value;
            }
        }
        
        [Required()]
        [MaxLength(255)]
        [StringLength(255)]
        [Display(Name = "Client ID")]
        public string ClientId {
            get {
                return this._clientId;
            }
            set {
                this._clientId = value;
            }
        }
        
        [Required()]
        [MaxLength(255)]
        [StringLength(255)]
        [Display(Name = "Client secret")]
        public string ClientSecret {
            get {
                return this._clientSecret;
            }
            set {
                this._clientSecret = value;
            }
        }
        
        [MaxLength(50)]
        [StringLength(50)]
        [Display(Name = "Client email")]
        public string ClientEmail {
            get {
                return this._clientEmail;
            }
            set {
                this._clientEmail = value;
            }
        }
        
        /// Child Users where [User].[AuthProvider] point to this entity (FK_User_AuthProvider)
        public virtual ICollection<UserModel> UsersModel { get; set; } = new HashSet<UserModel>();
        
        public override int GetHashCode() {
            int hash = 0;
            hash ^=Name.GetHashCode();
            return hash;
        }
        
        public override string ToString() {
            return Name
;
        }
        
        public override bool Equals(object obj) {
        bool result = false;

            if (obj is AuthProviderModel) {
                AuthProviderModel toCompare = (AuthProviderModel)obj;
              if(toCompare != null)
              {
                  result = Equals(toCompare);
              }
            }

            return result;
        }
        
        public virtual bool Equals(AuthProviderModel toCompare) {

        bool result = false;

            if (toCompare != null) {
                result = string.Compare(toCompare.Name, Name, true) == 0
;
            }

            return result;
        }
    }
}

